In [1]:
import pandas as pd

In [2]:
df1 = pd.read_csv('time_series.csv')
df2 = pd.read_csv('selected_stays.csv')

In [ ]:
df_count = data.stay_id.value_counts(dropna=False,sort=True)  
print(df_count)

In [ ]:
new_data = pd.DataFrame()
for i in range(len(df2)):
    query_id = df2.at[i,'stay_id']
    df_query = df1.query('stay_id == @query_id')
    df_query_fit = df_query.fillna(df_query.mean())
    new_data = new_data.append(df_query_fit)

In [6]:
new_data.to_csv('pre_process.csv')

The history saving thread hit an unexpected error (OperationalError('database is locked')).History will not be written to the database.


In [5]:
print(len(df2))

39742


In [6]:
print(df2.head(5))

    hadm_id   stay_id  gender  age               intime              outtime  \
0  27845175  33225641       0   32  2111-09-04 03:53:03  2111-09-11 18:11:57   
1  26542901  38808781       0   71  2150-01-23 20:12:28  2150-01-27 10:54:59   
2  21920312  38974640       1   63  2132-08-14 02:51:00  2132-08-18 11:25:46   
3  28403863  36458174       1   89  2133-08-29 14:38:00  2133-09-07 06:48:52   
4  21656279  30203390       1   86  2169-10-17 18:21:00  2169-10-20 22:33:00   

   dod       los  
0  NaN  7.596458  
1  NaN  3.612859  
2  NaN  4.357477  
3  NaN  8.674213  
4  NaN  3.175000  


In [28]:
import numpy as np
seq = np.arange(0,len(df2),1)

In [29]:
print(seq)

[    0     1     2 ... 39739 39740 39741]


In [38]:
from sklearn.model_selection import train_test_split
x_train,x_test,_,_ = train_test_split(seq, seq, test_size=0.1, random_state=42)

In [39]:
x_train = np.sort(x_train)
print(x_train)

[    0     2     3 ... 39739 39740 39741]


In [40]:
x_test = np.sort(x_test)
print(x_test)

[    1     4    13 ... 39716 39725 39736]


In [41]:
train_data = df2.loc[x_train,:]

In [42]:
print(train_data)

        hadm_id   stay_id  gender  age               intime  \
0      27845175  33225641       0   32  2111-09-04 03:53:03   
2      21920312  38974640       1   63  2132-08-14 02:51:00   
3      28403863  36458174       1   89  2133-08-29 14:38:00   
5      21263495  35437942       0   27  2115-12-03 22:54:00   
6      21306367  38405614       0   75  2110-12-06 00:47:41   
...         ...       ...     ...  ...                  ...   
39737  22818895  32564173       0   51  2122-11-21 17:48:13   
39738  22818895  35913063       0   51  2122-11-13 09:06:39   
39739  26248295  38087284       1   96  2196-11-15 23:45:24   
39740  26377098  31632048       1   54  2154-09-09 19:31:39   
39741  29623448  30591465       1   19  2152-02-20 10:13:58   

                   outtime  dod        los  
0      2111-09-11 18:11:57  NaN   7.596458  
2      2132-08-18 11:25:46  NaN   4.357477  
3      2133-09-07 06:48:52  NaN   8.674213  
5      2115-12-05 00:51:09  NaN   1.081354  
6      2110-12-06 

In [43]:
test_data = df2.loc[x_test,:]
print(test_data)

        hadm_id   stay_id  gender  age               intime  \
1      26542901  38808781       0   71  2150-01-23 20:12:28   
4      21656279  30203390       1   86  2169-10-17 18:21:00   
13     25983607  33747095       1   37  2164-08-16 23:24:00   
23     24333520  32494630       1   51  2171-02-03 01:34:04   
40     28399871  33785324       1   70  2131-07-19 21:42:35   
...         ...       ...     ...  ...                  ...   
39702  29089348  36632866       0   48  2171-03-27 14:00:04   
39714  21915782  35302101       1   84  2183-09-01 12:20:04   
39716  24345854  38566917       0   90  2117-03-08 00:43:00   
39725  21181190  38969365       1   46  2148-10-23 01:24:00   
39736  24121397  32605863       0   52  2132-09-03 21:31:00   

                   outtime  dod        los  
1      2150-01-27 10:54:59  NaN   3.612859  
4      2169-10-20 22:33:00  NaN   3.175000  
13     2164-08-17 15:23:45  NaN   0.666493  
23     2171-02-10 21:56:17  NaN   7.848762  
40     2131-08-02 

In [44]:
train_data.to_csv('train_stays.csv')

In [45]:
test_data.to_csv('test_stays.csv')